[package]
name = "import_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

invoke-witc = { path = "../../bindings/rust/invoke-witc" }
witc-abi = { path = "../../bindings/rust/witc-abi" }
