name: Release witc artifacts

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    name: Create Github Release
    env:
      VERSION: "${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2.8"
      - run: |
          stack install --local-bin-path ./
          mv witc witc-$VERSION-ubuntu

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: witc binary
          path: witc-${{ env.VERSION }}-ubuntu

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: witc-${{ env.VERSION }}-ubuntu
