name: Release witc artifacts

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    name: Create Github Release
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    env:
      SUFFIX: "${{ github.ref_name }}-${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2.8"
      - run: stack install --local-bin-path ./
      - if: matrix.os == 'windows'
        run: |
          mv witc.exe witc-$env:SUFFIX.exe
          echo "artifactPath=witc-$env:SUFFIX.exe" >> $env:GITHUB_ENV
      - if: matrix.os != 'windows'
        run: |
          mv witc witc-$SUFFIX
          echo "artifactPath=witc-$SUFFIX" >> $GITHUB_ENV

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: witc binary
          path: ${{ env.artifactPath }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.artifactPath }}
